default_language_version:
    python: python3.10
exclude: >
    (?x)^(
      .github/.*|
      development/ipython_profiles/.*|
      docs/.*|
      .*\.md
    )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        args: ['--line-length=79', '--experimental-string-processing']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear==20.11.1
        -   flake8-builtins==1.5.3
        -   flake8-comprehensions==3.3.1
        -   flake8-tidy-imports==4.2.1
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py38-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   --no-compile
        -   types-requests==2.25.6
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-use-type-annotations
